version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: eslint-plugin-standard
    versions:
    - 5.0.0
